from datetime import UTC, datetime

import pytest

from canvas_sdk.clients.twilio.constants.message_direction import MessageDirection
from canvas_sdk.clients.twilio.constants.message_status import MessageStatus
from canvas_sdk.clients.twilio.structures.message import Message
from canvas_sdk.tests.conftest import is_dataclass


def test_class() -> None:
    """Test Message dataclass has correct field types."""
    tested = Message
    fields = {
        "sid": str,
        "body": str,
        "date_created": datetime,
        "date_sent": datetime | None,
        "date_updated": datetime,
        "direction": MessageDirection,
        "number_from": str,
        "number_to": str,
        "price": str | None,
        "price_unit": str,
        "error_code": int | None,
        "error_message": str | None,
        "uri": str,
        "count_media": int | None,
        "count_segments": int,
        "status": MessageStatus,
        "sub_resource_uris": dict[str, str] | None,
    }
    assert is_dataclass(tested, fields)


@pytest.mark.parametrize(
    ("data", "expected"),
    [
        pytest.param(
            {
                "sid": "SM123",
                "body": "Hello World",
                "date_created": "Mon, 15 Dec 2025 10:30:00 +0000",
                "date_sent": "Mon, 15 Dec 2025 10:30:05 +0000",
                "date_updated": "Mon, 15 Dec 2025 10:30:10 +0000",
                "direction": "outbound-api",
                "from": "+11234567890",
                "to": "+11234567891",
                "price": "-0.00750",
                "price_unit": "USD",
                "error_code": None,
                "error_message": None,
                "uri": "/2010-04-01/Accounts/AC789/Messages/SM123",
                "num_media": 0,
                "num_segments": 1,
                "status": "sent",
                "subresource_uris": {"media": "/2010-04-01/Accounts/AC789/Messages/SM123/Media"},
            },
            Message(
                sid="SM123",
                body="Hello World",
                date_created=datetime(2025, 12, 15, 10, 30, 0, tzinfo=UTC),
                date_sent=datetime(2025, 12, 15, 10, 30, 5, tzinfo=UTC),
                date_updated=datetime(2025, 12, 15, 10, 30, 10, tzinfo=UTC),
                direction=MessageDirection.OUTBOUND_API,
                number_from="+11234567890",
                number_to="+11234567891",
                price="-0.00750",
                price_unit="USD",
                error_code=None,
                error_message=None,
                uri="/2010-04-01/Accounts/AC789/Messages/SM123",
                count_media=0,
                count_segments=1,
                status=MessageStatus.SENT,
                sub_resource_uris={"media": "/2010-04-01/Accounts/AC789/Messages/SM123/Media"},
            ),
            id="successful_outbound",
        ),
        pytest.param(
            {
                "sid": "SM456",
                "body": "Error message",
                "date_created": "Tue, 16 Dec 2025 14:20:00 +0000",
                "date_sent": None,
                "date_updated": "Tue, 16 Dec 2025 14:20:05 +0000",
                "direction": "outbound-api",
                "from": "+11234567892",
                "to": "+11234567893",
                "price": None,
                "price_unit": "USD",
                "error_code": 30007,
                "error_message": "Carrier violation",
                "uri": "/2010-04-01/Accounts/AC789/Messages/SM456",
                "num_media": 0,
                "num_segments": 1,
                "status": "failed",
                "subresource_uris": None,
            },
            Message(
                sid="SM456",
                body="Error message",
                date_created=datetime(2025, 12, 16, 14, 20, 0, tzinfo=UTC),
                date_sent=None,
                date_updated=datetime(2025, 12, 16, 14, 20, 5, tzinfo=UTC),
                direction=MessageDirection.OUTBOUND_API,
                number_from="+11234567892",
                number_to="+11234567893",
                price=None,
                price_unit="USD",
                error_code=30007,
                error_message="Carrier violation",
                uri="/2010-04-01/Accounts/AC789/Messages/SM456",
                count_media=0,
                count_segments=1,
                status=MessageStatus.FAILED,
                sub_resource_uris=None,
            ),
            id="failed_with_error",
        ),
        pytest.param(
            {
                "sid": "SM789",
                "body": "Incoming message",
                "date_created": "Wed, 17 Dec 2025 09:15:00 +0000",
                "date_sent": "Wed, 17 Dec 2025 09:15:00 +0000",
                "date_updated": "Wed, 17 Dec 2025 09:15:00 +0000",
                "direction": "inbound",
                "from": "+11234567894",
                "to": "+11234567895",
                "price": "-0.00750",
                "price_unit": "USD",
                "error_code": None,
                "error_message": None,
                "uri": "/2010-04-01/Accounts/AC789/Messages/SM789",
                "num_media": 2,
                "num_segments": 1,
                "status": "received",
                "subresource_uris": {"media": "/2010-04-01/Accounts/AC789/Messages/SM789/Media"},
            },
            Message(
                sid="SM789",
                body="Incoming message",
                date_created=datetime(2025, 12, 17, 9, 15, 0, tzinfo=UTC),
                date_sent=datetime(2025, 12, 17, 9, 15, 0, tzinfo=UTC),
                date_updated=datetime(2025, 12, 17, 9, 15, 0, tzinfo=UTC),
                direction=MessageDirection.INBOUND,
                number_from="+11234567894",
                number_to="+11234567895",
                price="-0.00750",
                price_unit="USD",
                error_code=None,
                error_message=None,
                uri="/2010-04-01/Accounts/AC789/Messages/SM789",
                count_media=2,
                count_segments=1,
                status=MessageStatus.RECEIVED,
                sub_resource_uris={"media": "/2010-04-01/Accounts/AC789/Messages/SM789/Media"},
            ),
            id="inbound_with_media",
        ),
    ],
)
def test_from_dict(data: dict, expected: Message) -> None:
    """Test Message.from_dict creates instance from dictionary with various scenarios."""
    test = Message
    result = test.from_dict(data)
    assert result == expected


@pytest.mark.parametrize(
    ("message", "expected"),
    [
        pytest.param(
            Message(
                sid="SM123",
                body="Hello World",
                date_created=datetime(2025, 12, 15, 10, 30, 0, tzinfo=UTC),
                date_sent=datetime(2025, 12, 15, 10, 30, 5, tzinfo=UTC),
                date_updated=datetime(2025, 12, 15, 10, 30, 10, tzinfo=UTC),
                direction=MessageDirection.OUTBOUND_API,
                number_from="+11234567890",
                number_to="+11234567891",
                price="-0.00750",
                price_unit="USD",
                error_code=None,
                error_message=None,
                uri="/2010-04-01/Accounts/AC789/Messages/SM123",
                count_media=0,
                count_segments=1,
                status=MessageStatus.SENT,
                sub_resource_uris={"media": "/2010-04-01/Accounts/AC789/Messages/SM123/Media"},
            ),
            {
                "sid": "SM123",
                "body": "Hello World",
                "date_created": "Mon, 15 Dec 2025 10:30:00 +0000",
                "date_sent": "Mon, 15 Dec 2025 10:30:05 +0000",
                "date_updated": "Mon, 15 Dec 2025 10:30:10 +0000",
                "created": "2025-12-15T10:30:00+0000",
                "sent": "2025-12-15T10:30:05+0000",
                "updated": "2025-12-15T10:30:10+0000",
                "direction": "outbound-api",
                "from": "+11234567890",
                "to": "+11234567891",
                "price": "-0.00750",
                "price_unit": "USD",
                "error_code": None,
                "error_message": None,
                "uri": "/2010-04-01/Accounts/AC789/Messages/SM123",
                "num_media": 0,
                "num_segments": 1,
                "status": "sent",
                "subresource_uris": {"media": "/2010-04-01/Accounts/AC789/Messages/SM123/Media"},
            },
            id="message_with_date_sent",
        ),
        pytest.param(
            Message(
                sid="SM456",
                body="No date sent",
                date_created=datetime(2025, 12, 16, 14, 20, 0, tzinfo=UTC),
                date_sent=None,
                date_updated=datetime(2025, 12, 16, 14, 20, 5, tzinfo=UTC),
                direction=MessageDirection.OUTBOUND_API,
                number_from="+11234567892",
                number_to="+11234567893",
                price=None,
                price_unit="USD",
                error_code=30007,
                error_message="Carrier violation",
                uri="/2010-04-01/Accounts/AC789/Messages/SM456",
                count_media=0,
                count_segments=1,
                status=MessageStatus.FAILED,
                sub_resource_uris=None,
            ),
            {
                "sid": "SM456",
                "body": "No date sent",
                "date_created": "Tue, 16 Dec 2025 14:20:00 +0000",
                "date_sent": None,
                "date_updated": "Tue, 16 Dec 2025 14:20:05 +0000",
                "created": "2025-12-16T14:20:00+0000",
                "sent": None,
                "updated": "2025-12-16T14:20:05+0000",
                "direction": "outbound-api",
                "from": "+11234567892",
                "to": "+11234567893",
                "price": None,
                "price_unit": "USD",
                "error_code": 30007,
                "error_message": "Carrier violation",
                "uri": "/2010-04-01/Accounts/AC789/Messages/SM456",
                "num_media": 0,
                "num_segments": 1,
                "status": "failed",
                "subresource_uris": None,
            },
            id="message_without_date_sent",
        ),
    ],
)
def test_to_dict(message: Message, expected: dict) -> None:
    """Test Message.to_dict converts instance to dictionary with formatted dates."""
    result = message.to_dict()
    assert result == expected
