name: "Install Canvas"
description: "Installs Canvas dependencies"


runs:
  using: "composite"
  steps:
    # Cache the project dependencies (everything in pyproject.toml).
    - name: Cache project dependencies
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: .venv
        key: project-dependencies-${{ hashFiles('**/poetry.lock') }}

    # Install project dependencies (bypassing the project, because we don't want to cache the Canvas code).
    - name: Install Dependencies
      run: poetry install --no-interaction --no-root
      shell: bash
      if: steps.cache-deps.outputs.cache-hit != 'true'

    # Install the project to make sure everything works and is synced.
    - name: Install Canvas
      shell: bash
      run: poetry install --no-interaction
