name: "Install Canvas"
description: "Installs Canvas dependencies"


runs:
  using: "composite"
  steps:
    # Cache the project dependencies (everything in pyproject.toml).
    - name: Cache project dependencies
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: .venv
        key: ${{runner.os}}-py${{env.PYTHON_VERSION}}-venv-${{ hashFiles('**/uv.lock') }}

    # Install project dependencies (bypassing the project, because we don't want to cache the Canvas code).
    - name: Install Dependencies
      run: uv sync --no-install-workspace
      shell: bash
      if: steps.cache-deps.outputs.cache-hit != 'true'

    # Regenerate the allowed imports
    - name: Regenerate allow imports
      run: uv run python -m plugin_runner.generate_allowed_imports
      shell: bash

    # Install the project to make sure everything works and is synced.
    - name: Install Canvas
      shell: bash
      run: uv sync
