# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: canvas_generated/messages/plugins.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'canvas_generated/messages/plugins.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'canvas_generated/messages/plugins.proto\"\x16\n\x14ReloadPluginsRequest\"(\n\x15ReloadPluginsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"%\n\x13ReloadPluginRequest\x12\x0e\n\x06plugin\x18\x01 \x01(\t\"\'\n\x14ReloadPluginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"%\n\x13UnloadPluginRequest\x12\x0e\n\x06plugin\x18\x01 \x01(\t\"\'\n\x14UnloadPluginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\xa9\x01\n\x0fRunAgentRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x11\n\tscope_key\x18\x02 \x01(\t\x12\x0e\n\x06run_id\x18\x03 \x01(\t\x12\x17\n\x0ftrigger_payload\x18\x04 \x01(\t\x12\x13\n\x0bplugin_name\x18\x05 \x01(\t\x12\x14\n\x0chandler_name\x18\x06 \x01(\t\x12\r\n\x05\x61\x63tor\x18\x07 \x01(\t\x12\x0e\n\x06source\x18\x08 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'canvas_generated.messages.plugins_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RELOADPLUGINSREQUEST']._serialized_start=43
  _globals['_RELOADPLUGINSREQUEST']._serialized_end=65
  _globals['_RELOADPLUGINSRESPONSE']._serialized_start=67
  _globals['_RELOADPLUGINSRESPONSE']._serialized_end=107
  _globals['_RELOADPLUGINREQUEST']._serialized_start=109
  _globals['_RELOADPLUGINREQUEST']._serialized_end=146
  _globals['_RELOADPLUGINRESPONSE']._serialized_start=148
  _globals['_RELOADPLUGINRESPONSE']._serialized_end=187
  _globals['_UNLOADPLUGINREQUEST']._serialized_start=189
  _globals['_UNLOADPLUGINREQUEST']._serialized_end=226
  _globals['_UNLOADPLUGINRESPONSE']._serialized_start=228
  _globals['_UNLOADPLUGINRESPONSE']._serialized_end=267
  _globals['_RUNAGENTREQUEST']._serialized_start=270
  _globals['_RUNAGENTREQUEST']._serialized_end=439
# @@protoc_insertion_point(module_scope)
