name: "Set sha"
description: "Outputs the SHA for the head and base commits, depending on if this is called on a pull_request or merge_queue"

outputs:
  head-sha:
    description: "SHA for the head commit"
    value: ${{ steps.set-head-sha.outputs.head-sha }}
  base-sha:
    description: "SHA for the base commit"
    value: ${{ steps.set-base-sha.outputs.base-sha }}
runs:
  using: "composite"
  steps:
    - name: Determine head sha
      id: set-head-sha
      shell: bash
      run: |
        if [ -z "${{ github.event.merge_group.head_sha }}" ]; then
          echo "head-sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
        else
          echo "head-sha=${{ github.event.merge_group.head_sha }}" >> $GITHUB_OUTPUT
        fi
    - name: Determine base sha
      id: set-base-sha
      shell: bash
      run: |
        if [ -z "${{ github.event.merge_group.base_sha }}" ]; then
          echo "base-sha=${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT
        else
          echo "base-sha=${{ github.event.merge_group.base_sha }}" >> $GITHUB_OUTPUT
        fi
